Add iOS Support
kurbos/bevy-shell-template pull request #28
Opened 2022-10-30 02:51 UTC by griffobeid

2022-10-30 13:56 UTC, simbleau requested changes

2022-10-30 13:56 UTC, simbleau commented on launchers/ios/src/main.rs
> +    info!("Starting launcher: Native");
`launcher: iOS`?

2022-10-30 13:56 UTC, simbleau commented on src/lib.rs
> +pub fn fullscreen_app() -> App {
Would rather have `fn app(fullscreen:bool)`

2022-10-30 13:56 UTC, simbleau commented on launchers/ios/run-ios-sim.sh
> +xcrun simctl launch --console booted "$BUNDLE_ID"
There are build scripts in Rust, would this be better?

2022-10-30 13:59 UTC, simbleau commented
I can do it, but if you prefer, we are also missing an iOS release in the .github (GitHub Actions) folder

2022-10-30 14:58 UTC, griffobeid commented on launchers/ios/run-ios-sim.sh
> +xcrun simctl launch --console booted "$BUNDLE_ID"
[cargo bundle](https://github.com/burtonageo/cargo-bundle) is doing a lot of the heavy lifting for us. It creates a Info.plist file and creates the `$APP_NAME.app` folder in the build dir. We could move that logic into a build script probably, but I don't think we will be able to avoid the `xcrun simctl` commands because those are booting an iOS simulator and installing the application onto it

2022-10-30 15:00 UTC, griffobeid commented on launchers/ios/src/main.rs
> +    info!("Starting launcher: Native");
Updated

2022-10-30 15:00 UTC, griffobeid commented on src/lib.rs
> +pub fn fullscreen_app() -> App {
Updated

2022-10-31 02:37 UTC, simbleau approved these changes

2022-10-31 02:46 UTC, merged